FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

COPY . .

RUN npm install

# Radix UI 아이콘 (명시적 설치)
# RUN npm install @radix-ui/react-icons

# ShadCN UI 컴포넌트 추가 (button, navigation-menu 등)
# RUN npx shadcn@latest add button
# RUN npx shadcn@latest add navigation-menu
# RUN npx shadcn@latest add label
# RUN npx shadcn@latest add card
# RUN npx shadcn@latest add checkbox

RUN npm run build



EXPOSE 3000

ENTRYPOINT ["npm", "run", "dev"]
